### ISSUE TITLE
Error in Example 4.2, 4.3, 4.4 and 5.2 - Attempt to reference field of non-structure array.

### ISSUE THREAD

**Issue by abdul-mannan-khan** [yu-jiang/RADPBook#7]
I have tried to run publishandpack.m in the repository. All the examples ran fine except Examples 4.2, 4.3, 4.4 and 5.2. Iterestingly, errors in all of these examples are common. As follows:

```
-->Publishing Example 4.2
Attempt to reference field of non-structure array.

Error in cvxprob (line 48)    
selected = cvx___.solvers.selected;

Error in cvx_begin (line 41)
assignin( 'caller', 'cvx_problem', cvxprob( varargin{:} ) );

Error in Ch4Ex2_main>LocalOnlinePI (line 227)
cvx_begin sdp
```

So, basically cvx__.solver.selected is not defined. Upon checking, I noticed that cvx__.solvers.selected is an empty array. 

I am wondering how to resolve this problem.

Dear @yu-jiang 
I know you could be very busy with your work and may not have much time. However, if it is some basic problem, it will be very grateful if you could have a look into it. Your efforts are highly appreciated. 

I look forward to having your kind response.  Thank you.

**Comment by yu-jiang** [comment]
Hi @abdul-mannan-khan , sorry I wasn't paying attention to this issue. This is a problem of cvx. Maybe there is an upgrade on their side. Let me do some investigation first ...

**Comment by yu-jiang** [comment]
Looks like this is a CVX issue. The cause seems to be CVX not properly started or setup.

[http://ask.cvxr.com/t/failed-to-use-cvx/664](url)

**Comment by abdul-mannan-khan** [comment]
I am sorry but the link you shared does not work. Could you please shed some more light. Thank you so much.
