### ISSUE TITLE
Running Code in MATLAB 2021

### ISSUE THREAD

**Issue by abdul-mannan-khan** [yu-jiang/RADPBook#8]
Dear Yu-Jiang, 

Thank you so much for providing these examples for everyone. 

I have some kind submissions. I have successfully run all the simulation in MATLAB 2021a. Before, I could go into details about the issue, please allow me to explain how to update it for MATLAB 2021a. 

To run all the codes successfully in MATLAB 2021a (except `Ch3Ex1_main.m`), we have to update

1. SOS Toolbox for MATLAB from [here](http://www.cds.caltech.edu/sostools/). 
2. CVX Toolbox from [here](http://cvxr.com/cvx/download/)
3. SDPT 3-4.0 Toolbox from [here](https://github.com/sqlp/sdpt3) 
After this all the codes run successfully except `Ch3Ex1_main.m`. Here are the errors. 

```
Error using mupadengine/feval_internal
Invalid input. Expected ')'.

Error in mupadengine/feval

Error in getdegrees (line 47)
coefmon = feval(symengine,'poly2list',p,vartable);

Error in sosvar (line 55)
Z = getdegrees(ZSym,sos.vartable,sos.symvartable);  %JA edit

Error in sospolyvar (line 56)
	[sos,V] = sosvar(sos,'poly',ZSym);

Error in Ch4Ex1_main (line 45)
[prog,V] = sospolyvar(prog,monomials([x1;x2;x3;x4],2:4),'wscoeff');
```

I have tried to trace the error in google [here](https://www.mathworks.com/matlabcentral/answers/521095-error-using-mupadengine-feval_internal-invalid-input-expected-error-in-mupadengine-feval) and [here](https://www.mathworks.com/matlabcentral/answers/498318-error-using-mupadengine-feval-line-187-invalid-equations). 

It seems that there is a problem in evaluating some terms in this example which cannot be evaluated as an input argument to the function. **Particularly, in [here](https://www.mathworks.com/matlabcentral/answers/498318-error-using-mupadengine-feval-line-187-invalid-equations) some solution is suggested but I do not know how to do it. Could you please help me fix it?** Your valuable effort is highly appreciated. Thank you so much.

**Comment by yu-jiang** [comment]
That seems to be a problem in sostools. Unfortunately that tool is not updated with newer versions of MATLAB.
