### ISSUE TITLE
Question in chapter 3

### ISSUE THREAD

**Issue by linbingjun** [yu-jiang/RADPBook#9]
Where does A*pw = B come from？from chapter 2?
% Off-Policy Learning. Solve the matrix A*pw = B
	A = [Phi -2*r*PsiU-2*r*PsiPsi*kron(w,eye(PsiLength))];
	% Note: To be consistent with the notations in (Y Jiang &  ZP Jiang,
	% TNNLS 2014), the above line should be replaced with
	% A = [Phi 2*r*PsiU-2*r*PsiPsi*kron(w,eye(PsiLength))];
	% i.e., consider u = w'*phi, not u = -w'*psi
	% In that case, the simpleSysWrapper should be called as
	% >> simpleSysWrapper(t,x,-w)
	B = -(CostQ + PsiPsi*kron(w,w));
	pw = A\B;

**Comment by yu-jiang** [comment]
Yes

**Comment by linbingjun** [comment]
thanks
